const newPostInitialValue = {
    title: '',
    roomType: null,
    province: null,
    district: null,
    ward: null,
    street: null,
    roomPrice: null,
    roomArea: null,
    roomQuantity: null,
    liveWithOwner: false,
    closeBathroom: false,
    haveWaterHeader: false,
    haveAirCondition: false,
    haveBalcony: false,
    waterElectricity: null,
    electricityPrice: null,
    waterPrice: null,
    description: null,
    numberOfDay: null,
    totalPrice: null,
    roomImageArr: [],
    kitchenType: null,
    publicLocationNearby: null,
};

export default newPostInitialValue;
