const newPostInitialValue = {
    title: '',
    roomType: {},
    province: {},
    district: null,
    ward: null,
    street: '',
    roomPrice: 0,
    roomArea: {},
    roomQuantity: 0,
    liveWithOwner: false,
    closeBathroom: false,
    haveWaterHeader: false,
    haveAirCondition: false,
    haveBalcony: false,
    waterElectricity: 'rent',
    electricityPrice: 0,
    waterPrice: 0,
    description: '',
    roomImageArr: [],
    kitchenType: {},
    publicLocationNearby: '',
    packageType: {
        value: 1,
        label: 'Đăng theo tuần',
        price: 1000,
        type: 'tuần',
        day: 7,
    },
    numberOfTime: 1,
    owner: {},
    roomOption: '',
};

export default newPostInitialValue;
