const newPostInitialValue = {
    title: null,
    roomType: {},
    province: null,
    district: null,
    ward: null,
    street: null,
    roomPrice: null,
    roomArea: null,
    roomQuantity: null,
    liveWithOwner: false,
    closeBathroom: false,
    haveWaterHeader: false,
    haveAirCondition: false,
    haveBalcony: false,
    waterElectricity: 'rent',
    electricityPrice: null,
    waterPrice: null,
    description: null,
    numberOfDay: null,
    totalPrice: null,
    roomImageArr: [],
    kitchenType: null,
    publicLocationNearby: null,
    package: { value: 1, label: 'Đăng theo tuần', price: 1000, type: 'tuần' },
    numberOfTime: 1,
    owner: {},
};

export default newPostInitialValue;
